### ISSUE TITLE
添加 Google Analysis 的规则

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ivysrono/URLRedirectorRules#2]
把 google-analysis.com 重定向到 0.0.0.0

**Comment by ivysrono** [comment]
第一，我没试过这个扩展的规则能否将域名重定向到IP，尤其是特殊IP地址。
第二，能做这个的工具无数，为何一定要用这个扩展？用专门的广告过滤扩展/软件不是更合适么？
第三，也是最重要的，我这的规则基本是给自己用的，你自己的需求应该自己维护。
