### ISSUE TITLE
能不能移植规则到 Header Editor

### ISSUE THREAD

**Issue by sgrjyb** [ivysrono/URLRedirectorRules#3]

**Comment by ivysrono** [comment]
等HE再成熟点再说，至少等批量删除/覆盖式导入/同步等功能做得差不多了再干。

**Comment by sgrjyb** [comment]
唔

**Comment by sgrjyb** [comment]
更新了，可以适配了吗？

**Comment by ivysrono** [comment]
官方已经提供了转换工具，你可以自己搞嘛。
因为同步还没有，我个人暂时还不会迁移。

**Comment by ivysrono** [comment]
https://github.com/FirefoxBar/HeaderEditor/issues/10
https://github.com/FirefoxBar/HeaderEditor/issues/14
至少还要等待这两个方面得改进才适合全面迁移。
